### PR TITLE
Fix resource passed conditions

### PR DESCRIPTION
**Pull request by bradfordboyle**

### CODE REVIEW

**Comment by bradfordboyle** [comment]
This PR contains two commits:

- first commit fixes yaml indentation and can skipped in reviewing
- second commit adds passed conditions for greenplum-database-release resource

Please review the second commit.

**Comment by baotingfang** [comment]
I think we need to fix the `license_file` resource passed conditions too.

**Comment by amilkh** [comment]
> I think we need to fix the `license_file` resource passed conditions too.

+1

**Comment by amilkh** [comment]
Curious what tool you used to fix the indentation? LGTM

**Comment by bradfordboyle** [comment]
> Curious what tool you used to fix the indentation? LGTM

I used [yamllint](https://github.com/adrienverge/yamllint) with the following config:

```yml
---

rules:
  braces: enable
  brackets: enable
  colons: enable
  commas: enable
  comments:
    level: warning
  comments-indentation:
    level: warning
  document-end: disable
  document-start:
    level: warning
  empty-lines: enable
  empty-values: enable
  hyphens: enable
  indentation:
    spaces: 2
    indent-sequences: false
  key-duplicates: enable
  key-ordering: disable
  #line-length: enable
  new-line-at-end-of-file: enable
  new-lines: enable
  octal-values: enable
  quoted-strings: disable
  trailing-spaces: enable
  truthy:
    level: warning
```

I think fixed the indentation based on the emitted warnings.

**Comment by amilkh** [comment]
Nice! reminded me about this nice yamllint pipeline you made! https://releng.ci.gpdb.pivotal.io/teams/main/pipelines/yamllint

**Pull request merged**
